### ISSUE TITLE
Bagaimanakah cara pakai nya?

### ISSUE THREAD

**Issue by APdev93** [NajmyW/AplikasiPenghitungUmur#1]
How

**Comment by NajmyW** [comment]
silahkan dibaca Readme.md nya, udah di pasang

**Comment by APdev93** [comment]
Terima kasih, aplikasi Anda sangat berguna.

**Comment by APdev93** [comment]
| Header | Header | Header |
|--------|--------|--------|
| 1 | 1 | 1 |
| 1 | 1 | 1 |
| Cell | Cell | Cell |
